baseURL = "https://m-ligtenberg.github.io/CuliacanRTS/"
languageCode = "en-us"
title = "CuliacanRTS devblog"
disableKinds = ["section"]
disqusShortname = ""
pygmentsCodeFences = false
pygmentsUseClasses = false
minify = true

# Suppress raw HTML warnings in Markdown rendering

# Suppress raw HTML warnings in Markdown rendering
ignoreLogs = ["warning-goldmark-raw-html"]

[pagination]
  pagerSize = 999


[taxonomies]
  tag = "tags"
  author = "authors"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true


[params]
  description = ""
  author = ""
  copyright = ""
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = ""
  github = ""
  facebook = ""
  og_image = ""
  sitename = ""
  twitter = ""

[permalinks]
  posts = "/:year/:month/:day/:contentbasename"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20

  [[menu.main]]
    identifier = "rss"
    name       = "RSS"
    url        = "/atom.xml"
    weight     = -10
