baseURL = "https://m-ligtenberg.github.io/CuliacanRTS/"
languageCode = "en-us"
title = "CuliacanRTS devblog"
disableKinds = ["section"]
disqusShortname = ""
pygmentsCodeFences = false
pygmentsUseClasses = false

[pagination]
  pagerSize = 999
minify = true
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[params]
  description = "Battle of Culiacán RTS Development Blog"
  author = "CuliacanRTS Team"
  copyright = ""
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = ""
  github = ""
  facebook = ""
  og_image = ""
  sitename = ""
  twitter = ""

[permalinks]
  posts = "/:year/:month/:day/:contentbasename"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20

  [[menu.main]]
    identifier = "rss"
    name       = "RSS"
    url        = "/atom.xml"
    weight     = -10
