name: Deploy Hugo site to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches:
      - main
      - master
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    # GitHub-hosted runners automatically enable `set -eo pipefail` for Bash shells
    shell: bash

jobs:

  build:
    name: Build with Hugo
    runs-on: ubuntu-latest
    env:
      DART_SASS_VERSION: 1.89.2
      HUGO_VERSION: 0.148.0
      HUGO_ENVIRONMENT: production
      TZ: America/Los_Angeles
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb \
            https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: |
          wget -O ${{ runner.temp }}/dart-sass.tar.gz \
            https://github.com/sass/dart-sass/releases/download/${{ env.DART_SASS_VERSION }}/dart-sass-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
          tar -xf ${{ runner.temp }}/dart-sass.tar.gz --directory ${{ runner.temp }}
          sudo mv ${{ runner.temp }}/dart-sass/ /usr/local/bin
          echo "/usr/local/bin/dart-sass" >> $GITHUB_PATH

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node.js dependencies
        run: |
          cd public
          if [[ -f package-lock.json || -f npm-shrinkwrap.json ]]; then npm ci; fi

      - name: Generate development content
        run: |
          mkdir -p public/content/posts
          
          # Create live changelog post
          if [ -f CHANGELOG.md ]; then
            echo "---" > public/content/posts/changelog.md
            echo "title: \"Live Changelog\"" >> public/content/posts/changelog.md
            echo "date: $(date -Iseconds)" >> public/content/posts/changelog.md
            echo "draft: false" >> public/content/posts/changelog.md
            echo "tags: [\"changelog\", \"updates\", \"development\"]" >> public/content/posts/changelog.md
            echo "description: \"Automatically updated changelog from the main repository\"" >> public/content/posts/changelog.md
            echo "---" >> public/content/posts/changelog.md
            echo "" >> public/content/posts/changelog.md
            echo "This changelog is automatically updated from the main repository on every commit." >> public/content/posts/changelog.md
            echo "" >> public/content/posts/changelog.md
            cat CHANGELOG.md >> public/content/posts/changelog.md
          fi

          # Create development status post from CLAUDE.md
          if [ -f CLAUDE.md ]; then
            echo "---" > public/content/posts/development-status.md
            echo "title: \"Development Status\"" >> public/content/posts/development-status.md
            echo "date: $(date -Iseconds)" >> public/content/posts/development-status.md
            echo "draft: false" >> public/content/posts/development-status.md
            echo "tags: [\"development\", \"status\", \"features\", \"phase\"]" >> public/content/posts/development-status.md
            echo "description: \"Current development status and feature implementation\"" >> public/content/posts/development-status.md
            echo "---" >> public/content/posts/development-status.md
            echo "" >> public/content/posts/development-status.md
            echo "This development status is automatically updated from the main repository." >> public/content/posts/development-status.md
            echo "" >> public/content/posts/development-status.md
            cat CLAUDE.md >> public/content/posts/development-status.md
          fi

          # Create recent commits post
          echo "---" > public/content/posts/recent-commits.md
          echo "title: \"Recent Development Activity\"" >> public/content/posts/recent-commits.md
          echo "date: $(date -Iseconds)" >> public/content/posts/recent-commits.md
          echo "draft: false" >> public/content/posts/recent-commits.md
          echo "tags: [\"commits\", \"development\", \"activity\"]" >> public/content/posts/recent-commits.md
          echo "description: \"Latest commits and development activity\"" >> public/content/posts/recent-commits.md
          echo "---" >> public/content/posts/recent-commits.md
          echo "" >> public/content/posts/recent-commits.md
          echo "## Recent Development Activity" >> public/content/posts/recent-commits.md
          echo "" >> public/content/posts/recent-commits.md
          echo "Latest commits to the repository:" >> public/content/posts/recent-commits.md
          echo "" >> public/content/posts/recent-commits.md
          git log --oneline -10 --pretty=format:"- **%h** %s (%an, %ar)" >> public/content/posts/recent-commits.md

      - name: Restore Hugo cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/hugo_cache
          key: hugo-${{ github.run_id }}
          restore-keys: |
            hugo-

      - name: Configure Git
        run: git config core.quotepath false

      - name: Build site with Hugo
        run: |
          hugo --source public \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --cacheDir "${{ runner.temp }}/hugo_cache"

      - name: Save Hugo cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ runner.temp }}/hugo_cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/public

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
